server:
  port: 8181
spring:
  main:
    allow-circular-references: true
    h2:
      console.enabled: true
    datasource:
      url: jdbc:h2:mem:dcbapp
      driverClassName: org.h2.Driver
      username: sa
      password: password
  # we disable Hibernate automatic schema creation
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

