server:
  port: 8181
spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
    properties:
      hibernate:
        format_sql: true