drop table if exists member cascade;
drop table if exists roles cascade;
create table member
(
    id         bigint generated by default as identity (start with 2) primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    role       varchar(45),
    createdOn  datetime,
    modifiedOn datetime,
    createdBy  varchar(45),
    modifiedBy varchar(45)
);
create table roles
(
    id   bigint generated by default as identity (start with 2) primary key,
    name varchar(255),
    createdOn  datetime,
    modifiedOn datetime,
    createdBy  varchar(45),
    modifiedBy varchar(45)
);
create table users_roles
(
    id         bigint generated by default as identity (start with 2) primary key,
    name       varchar(255),
    user_id    bigint,
    role_id    bigint,
    createdOn  datetime,
    modifiedOn datetime,
    createdBy  varchar(45),
    modifiedBy varchar(45)
);

alter table if exists member
    add constraint UKmbmcqelty0fbrvxp1q58dn57t unique (email);


alter table if exists users_roles
    add constraint FKaxm251aosah2cgsmksb5xy7if
    foreign key (role_id)
    references roles;

alter table if exists users_roles
    add constraint FK66pv2grnj7pivu4d3y8s5gxgx
    foreign key (user_id)
    references member;

